//
// Generated file, do not edit! Created by nedtool 5.6 from packet30.msg.
//

#ifndef __PACKET30_M_H
#define __PACKET30_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>packet30.msg:1</tt> by nedtool.
 * <pre>
 * packet packet30
 * {
 *     int src;
 *     int dest;
 *     int hop = 0;
 * }
 * </pre>
 */
class packet30 : public ::omnetpp::cPacket
{
  protected:
    int src;
    int dest;
    int hop;

  private:
    void copy(const packet30& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const packet30&);

  public:
    packet30(const char *name=nullptr, short kind=0);
    packet30(const packet30& other);
    virtual ~packet30();
    packet30& operator=(const packet30& other);
    virtual packet30 *dup() const override {return new packet30(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getSrc() const;
    virtual void setSrc(int src);
    virtual int getDest() const;
    virtual void setDest(int dest);
    virtual int getHop() const;
    virtual void setHop(int hop);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const packet30& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, packet30& obj) {obj.parsimUnpack(b);}


#endif // ifndef __PACKET30_M_H

